### ISSUE TITLE
Traceback occur when broken pipe

### ISSUE THREAD

**Issue by eax64** [wapiflapi/hx#1]
If we pipe the output of hx on a program that close the pipe before the end of the stream, we get a python traceback.

Step to reproduce: `cat /usr/bin/ls | hx |head`

What happen:

```
$ cat /usr/bin/ls | hx |head
00000000  7f454c46 02010100 00000000 00000000  ·ELF············
00000010  02003e00 01000000 d0484000 00000000  ··>······H@·····
00000020  40000000 00000000 78c70100 00000000  @·······x·······
00000030  00000000 40003800 09004000 1c001b00  ····@·8·␣·@·␣···
00000040  06000000 05000000 40000000 00000000  ········@·······
00000050  40004000 00000000 40004000 00000000  @·@·····@·@·····
00000060  f8010000 00000000 f8010000 00000000  ················
00000070  08000000 00000000 03000000 04000000  ················
00000080  38020000 00000000 38024000 00000000  8·······8·@·····
00000090  38024000 00000000 1c000000 00000000  8·@·····␣·······
Traceback (most recent call last):
  File "/usr/bin/hx", line 4, in <module>
    __import__('pkg_resources').run_script('hx==0.2.0', 'hx')
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python3.4/site-packages/hx-0.2.0-py3.4.egg/EGG-INFO/scripts/hx", line 38, in <module>
    dumper.dump(args.file)
  File "/usr/lib/python3.4/site-packages/hx-0.2.0-py3.4.egg/hx/dumper.py", line 52, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/hx-0.2.0-py3.4.egg/hx/dumper.py", line 79, in dump
    self.start_line(addr)
  File "/usr/lib/python3.4/site-packages/hx-0.2.0-py3.4.egg/hx/dumper.py", line 141, in start_line
    nil, colorama.Fore.WHITE, txt)
  File "/usr/lib/python3.4/site-packages/hx-0.2.0-py3.4.egg/hx/dumper.py", line 90, in output
    print(*args, end='', sep='')
  File "/usr/lib/python3.4/site-packages/colorama-0.3.3-py3.4.egg/colorama/ansitowin32.py", line 36, in write
  File "/usr/lib/python3.4/site-packages/colorama-0.3.3-py3.4.egg/colorama/ansitowin32.py", line 133, in write
  File "/usr/lib/python3.4/site-packages/colorama-0.3.3-py3.4.egg/colorama/ansitowin32.py", line 161, in write_and_convert
  File "/usr/lib/python3.4/site-packages/colorama-0.3.3-py3.4.egg/colorama/ansitowin32.py", line 167, in write_plain_text
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <colorama.ansitowin32.StreamWrapper object at 0x7f0c7b5436a0>
BrokenPipeError: [Errno 32] Broken pipe
```

What should happen: a clean exit of hx when the pipe is closed.

**Comment by wapiflapi** [comment]
Sorry for the noise. Was experimenting github.
